writing-technical-reports:
  stage: build
  script:
  - cd latex
  - ./weave.py writing-technical-reports
  - cp writing-technical-reports/*.pdf ../su17-writing-technical-reports-v1.pdf
  artifacts:
    paths:
    - su17-writing-technical-reports-v1.pdf
  tags:
  - latex
  only:
  - master
  - triggers
